services:
  procsapp:
    build: ./flask/procs-app
    image: procs-app
    ports:
      - "5000:5000"
    network_mode: bridge
    container_name: procs-app
  storageapp:
    build: ./flask/storage-app
    image: storage-app
    links:
      - db
    ports:
      - "4000:4000"
    network_mode: bridge
    container_name: storage-app
  userapp:
    build: ./flask/user-app
    image: user-app
    links:
      - db
    ports:
      - "3000:3000"
    network_mode: bridge
    container_name: user-app
  db:
    image: mysql:debian
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    network_mode: bridge
    container_name: mysql
  frontapp:
    build: ./angular/front-app
    image: front-app
    ports:
      - "4200:4200"
    network_mode: bridge      
    container_name: front-app