services:
  getapp:
    build: ./flask/get-app
    image: get-app
    ports:
      - "5000:5000"
    network_mode: bridge
    container_name: get-app
  postapp:
    build: ./flask/post-app
    image: post-app
    links:
      - db
    ports:
      - "4000:4000"
    network_mode: bridge
    container_name: post-app
  userapp:
    build: ./flask/user-app
    image: user-app
    links:
      - db
    ports:
      - "3000:3000"
    network_mode: bridge
    container_name: user-app
  db:
    image: mysql:debian
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    network_mode: bridge
    container_name: mysql
  frontapp:
    build: ./angular/front-app
    image: front-app
    ports:
      - "4200:4200"
    network_mode: bridge      
    container_name: front-app